[project]
name = "netsniff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=46.0.3",
    "dotenv>=0.9.9",
    "psutil>=7.0.0",
    "pyinstaller>=6.16.0",
    "requests>=2.32.5",
    "scapy>=2.6.1",
]
